name: Store Multiple Build Scan URLs As Artifacts

on:
  push:
    branches: 'ne/buildscan-recipes'

jobs:
  test_job:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        id: gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test

      - name: Save Build Scan Log
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: buildscan-test
          path: 'buildscan.log'

  assemble_job:
    name: Assemble
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Assemble
        id: gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assembleDebug

      - name: Save Build Scan Log
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: buildscan-assemble
          path: 'buildscan.log'