name: Add Buildscan PR Comment For Single Job

on:
  pull_request:
    branches: 'ne/buildscan-recipes'

jobs:
  assemble:
    name: Assemble Debug
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - id: gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assembleDebug

      - name: Add Build Scan URLs to Pull Request
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            **Buildscan url for run [${{ github.run_id }}](https://github.com/n8ebel/GitHubActionsAutomationSandbox/actions/runs/${{ github.run_id }})**
            ${{ steps.gradle.outputs.build-scan-url }}